apiVersion: 1

deleteDatasources:
  - name: grafana-postgresql-datasource
    orgId: 1

datasources:
  - name: grafana-postgresql-datasource
    type: postgres
    uid: postgres
    access: proxy
    url: postgres:5432
    database: fraud_db
    user: fraud_user
    secureJsonData:
      password: fraud_pass
    jsonData:
      sslmode: disable
      postgresVersion: 1500
      timescaledb: false
    isDefault: false
    editable: true